In [2]:
import numpy as np



In [5]:
a = np.ndarray(shape=(2,3), order='C')
for i in range(6): a.itemset(i, i+1)

print(a)

print(a.ravel(order='K'))

print(a[1,2])

#need to explore this more before i rebuild entire program...
#https://stackoverflow.com/questions/20341614/numpy-array-row-major-and-column-major

[[1. 2. 3.]
 [4. 5. 6.]]
[1. 2. 3. 4. 5. 6.]
6.0
